const AlphabetList = {
  english: {
    lowerCase: [
      { title: "a", value: "a", id: 1.5 },
      { title: "b", value: "b", id: 2.5 },
      { title: "c", value: "c", id: 3.5 },
      { title: "d", value: "d", id: 4.5 },
      { title: "e", value: "e", id: 5.5 },
      { title: "f", value: "f", id: 6.5 },
      { title: "g", value: "g", id: 7.5 },
      { title: "h", value: "h", id: 8.5 },
      { title: "i", value: "i", id: 9.5 },
      { title: "j", value: "j", id: 10.5 },
      { title: "k", value: "k", id: 11.5 },
      { title: "l", value: "l", id: 12.5 },
      { title: "m", value: "m", id: 13.5 },
      { title: "n", value: "n", id: 14.5 },
      { title: "o", value: "o", id: 15.5 },
      { title: "p", value: "p", id: 16.5 },
      { title: "q", value: "q", id: 17.5 },
      { title: "r", value: "r", id: 18.5 },
      { title: "s", value: "s", id: 19.5 },
      { title: "t", value: "t", id: 20.5 },
      { title: "u", value: "u", id: 21.5 },
      { title: "v", value: "v", id: 22.5 },
      { title: "w", value: "w", id: 23.5 },
      { title: "x", value: "x", id: 24.5 },
      { title: "y", value: "y", id: 25.5 },
      { title: "z", value: "z", id: 26.5 }
    ],
    capitalized: [
      { title: "A", value: "A", id: 1 },
      { title: "B", value: "B", id: 2 },
      { title: "C", value: "C", id: 3 },
      { title: "D", value: "D", id: 4 },
      { title: "E", value: "E", id: 5 },
      { title: "F", value: "F", id: 6 },
      { title: "G", value: "G", id: 7 },
      { title: "H", value: "H", id: 8 },
      { title: "I", value: "I", id: 9 },
      { title: "J", value: "J", id: 10 },
      { title: "K", value: "K", id: 11 },
      { title: "L", value: "L", id: 12 },
      { title: "M", value: "M", id: 13 },
      { title: "N", value: "N", id: 14 },
      { title: "O", value: "O", id: 15 },
      { title: "P", value: "P", id: 16 },
      { title: "Q", value: "Q", id: 17 },
      { title: "R", value: "R", id: 18 },
      { title: "S", value: "S", id: 19 },
      { title: "T", value: "T", id: 20 },
      { title: "U", value: "U", id: 21 },
      { title: "V", value: "V", id: 22 },
      { title: "W", value: "W", id: 23 },
      { title: "X", value: "X", id: 24 },
      { title: "Y", value: "Y", id: 25 },
      { title: "Z", value: "Z", id: 26 }
    ]
  },
  spanish: {
    lowerCase: [
      { title: "a", value: "a", id: 1.5 },
      { title: "\xE1", value: "\xE1", id: 27.5 },
      { title: "b", value: "b", id: 2.5 },
      { title: "c", value: "c", id: 3.5 },
      { title: "d", value: "d", id: 4.5 },
      { title: "e", value: "e", id: 5.5 },
      { title: "\xE9", value: "\xE9", id: 28.5 },
      { title: "f", value: "f", id: 6.5 },
      { title: "g", value: "g", id: 7.5 },
      { title: "h", value: "h", id: 8.5 },
      { title: "i", value: "i", id: 9.5 },
      { title: "\xED", value: "\xED", id: 29.5 },
      { title: "j", value: "j", id: 10.5 },
      { title: "k", value: "k", id: 11.5 },
      { title: "l", value: "l", id: 12.5 },
      { title: "m", value: "m", id: 13.5 },
      { title: "n", value: "n", id: 14.5 },
      { title: "\xF1", value: "\xF1", id: 30.5 },
      { title: "o", value: "o", id: 15.5 },
      { title: "\xF3", value: "\xF3", id: 31.5 },
      { title: "p", value: "p", id: 16.5 },
      { title: "q", value: "q", id: 17.5 },
      { title: "r", value: "r", id: 18.5 },
      { title: "s", value: "s", id: 19.5 },
      { title: "t", value: "t", id: 20.5 },
      { title: "u", value: "u", id: 21.5 },
      { title: "\xFA", value: "\xFA", id: 32.5 },
      { title: "v", value: "v", id: 22.5 },
      { title: "w", value: "w", id: 23.5 },
      { title: "x", value: "x", id: 24.5 },
      { title: "y", value: "y", id: 25.5 },
      { title: "\xFD", value: "\xFD", id: 33.5 },
      { title: "z", value: "z", id: 26.5 }
    ],
    capitalized: [
      { title: "A", value: "A", id: 1 },
      { title: "\xC1", value: "\xC1", id: 27 },
      { title: "B", value: "B", id: 2 },
      { title: "C", value: "C", id: 3 },
      { title: "D", value: "D", id: 4 },
      { title: "E", value: "E", id: 5 },
      { title: "\xC9", value: "\xC9", id: 28 },
      { title: "F", value: "F", id: 6 },
      { title: "G", value: "G", id: 7 },
      { title: "H", value: "H", id: 8 },
      { title: "I", value: "I", id: 9 },
      { title: "\xCD", value: "\xCD", id: 29 },
      { title: "J", value: "J", id: 10 },
      { title: "K", value: "K", id: 11 },
      { title: "L", value: "L", id: 12 },
      { title: "M", value: "M", id: 13 },
      { title: "N", value: "N", id: 14 },
      { title: "\xD1", value: "\xD1", id: 30 },
      { title: "O", value: "O", id: 15 },
      { title: "\xD5", value: "\xD5", id: 31 },
      { title: "P", value: "P", id: 16 },
      { title: "Q", value: "Q", id: 17 },
      { title: "R", value: "R", id: 18 },
      { title: "S", value: "S", id: 19 },
      { title: "T", value: "T", id: 20 },
      { title: "U", value: "U", id: 21 },
      { title: "\xDA", value: "\xDA", id: 32 },
      { title: "V", value: "V", id: 22 },
      { title: "W", value: "W", id: 23 },
      { title: "X", value: "X", id: 24 },
      { title: "Y", value: "Y", id: 25 },
      { title: "Z", value: "Z", id: 26 }
    ]
  }
};

export default AlphabetList;
